# Generated by Django 4.1 on 2022-08-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('streamer_name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='start time')),
            ],
        ),
    ]
