# Generated by Django 4.1 on 2022-08-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitchsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamdata',
            name='url',
        ),
        migrations.AddField(
            model_name='streamdata',
            name='language',
            field=models.CharField(default='en', max_length=200),
        ),
    ]
