import os

MIN_TO_NEW_STREAM = 5
MIN_VIEW_COUNT = 5
TWITCH_SPOTLIGHT_APP_ID = os.environ['TWITCH_SPOTLIGHT_APP_ID']
TWITCH_SPOTLIGHT_APP_SECRET = os.environ['TWITCH_SPOTLIGHT_APP_SECRET']
STREAM_LANGUAGE = 'pt'
